DROP TABLE IF EXISTS ADMINS
DROP TABLE IF EXISTS SCHEDULE_ROWS
DROP TABLE IF EXISTS SCHEDULES
DROP TABLE IF EXISTS SERVICES
DROP TABLE IF EXISTS APPOINTMENT_SERVICES
DROP TABLE IF EXISTS APPOINTMENTS
DROP TABLE IF EXISTS FILES
DROP TABLE IF EXISTS USERS
DROP TABLE IF EXISTS HAIRDRESSERS

DROP PROCEDURE IF EXISTS SP_ASSIGN_TOKEN
DROP PROCEDURE IF EXISTS SP_COMPARE_ROLE

/****** Object:  Table ADMINS    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ADMINS(
	hairdresser_id int NOT NULL,
	user_id int NOT NULL,
	role tinyint NOT NULL,
 CONSTRAINT PK_ADMINS PRIMARY KEY CLUSTERED 
(
	hairdresser_id ASC,
	user_id ASC
))

GO
/****** Object:  Table APPOINTMENT_SERVICES    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE APPOINTMENT_SERVICES(
	appointment_id int NOT NULL,
	service_id int NOT NULL,
 CONSTRAINT PK_APPOINTMENT_SERVICES PRIMARY KEY CLUSTERED 
(
	appointment_id ASC,
	service_id ASC
))

GO
/****** Object:  Table APPOINTMENTS    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE APPOINTMENTS(
	appointment_id int NOT NULL,
	user_id int NOT NULL,
	hairdresser_id int NOT NULL,
	date date NOT NULL,
	time time(0) NOT NULL,
	status int NOT NULL,
 CONSTRAINT PK_APPOINTMENTS PRIMARY KEY CLUSTERED 
(
	appointment_id ASC
))

GO
/****** Object:  Table FILES    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE FILES(
	file_id int NOT NULL,
	name nvarchar(50) NOT NULL,
	alternate_text nvarchar(50) NULL,
	folder int NOT NULL,
 CONSTRAINT PK_FILES_1 PRIMARY KEY CLUSTERED 
(
	file_id ASC
))

GO
/****** Object:  Table HAIRDRESSERS    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE HAIRDRESSERS(
	hairdresser_id int NOT NULL,
	name nvarchar(60) NOT NULL,
	number_phone nvarchar(20) NULL,
	address nvarchar(200) NOT NULL,
	postal_code int NOT NULL,
	token nvarchar(100) NULL,
 CONSTRAINT PK_HAIRDRESSERS PRIMARY KEY CLUSTERED 
(
	hairdresser_id ASC
))

GO
/****** Object:  Table SCHEDULE_ROWS    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SCHEDULE_ROWS(
	schedule_row_id int NOT NULL,
	schedule_id int NOT NULL,
	start_time time(0) NOT NULL,
	end_time time(0) NOT NULL,
	monday bit NOT NULL,
	tuesday bit NOT NULL,
	wednesday bit NOT NULL,
	thursday bit NOT NULL,
	friday bit NOT NULL,
	saturday bit NOT NULL,
	sunday bit NOT NULL,
 CONSTRAINT PK_SCHEDULE_ROWS PRIMARY KEY CLUSTERED 
(
	schedule_row_id ASC
))

GO
/****** Object:  Table SCHEDULES    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SCHEDULES(
	schedule_id int NOT NULL,
	hairdresser_id int NOT NULL,
	name nvarchar(50) NOT NULL,
	active bit NOT NULL,
 CONSTRAINT PK_SCHEDULES PRIMARY KEY CLUSTERED 
(
	schedule_id ASC
))

GO
/****** Object:  Table SERVICES    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SERVICES(
	service_id int NOT NULL,
	hairdresser_id int NOT NULL,
	name nvarchar(50) NOT NULL,
	price decimal(5, 2) NOT NULL,
	daprox tinyint NOT NULL,
 CONSTRAINT PK_SERVICES PRIMARY KEY CLUSTERED 
(
	service_id ASC
))

GO
/****** Object:  Table USERS    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE USERS(
	user_id int NOT NULL,
	password varbinary(max) NOT NULL,
	password_read nvarchar(50) NOT NULL,
	salt nvarchar(50) NOT NULL,
	email nvarchar(50) NOT NULL,
	email_validated bit NOT NULL,
	last_name nvarchar(50) NULL,
	name nvarchar(50) NOT NULL,
	number_phone nvarchar(20) NULL,
	temp_token nvarchar(100) NULL,
 CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED 
(
	user_id ASC
))

GO
INSERT ADMINS (hairdresser_id, user_id, role) VALUES (1, 1, 1)
GO
INSERT HAIRDRESSERS (hairdresser_id, name, number_phone, address, postal_code, token) VALUES (1, N'El Haddadi - Peluquería Caballeros', N'918 51 34 56', N'C/. Travesía de la Venta 1 Local Nº 2', 28400, N'7hFSMXWUSqYiJ3vzpQoJYbVbs5JoapYNgRiph1edTyNzE79LOx')
GO
INSERT SCHEDULE_ROWS (schedule_row_id, schedule_id, start_time, end_time, monday, tuesday, wednesday, thursday, friday, saturday, sunday) VALUES (1, 1, CAST(N'08:00:00' AS Time), CAST(N'14:00:00' AS Time), 1, 1, 1, 1, 1, 0, 0)
GO
INSERT SCHEDULES (schedule_id, hairdresser_id, name, active) VALUES (1, 1, N'Horario General', 1)
GO
INSERT USERS (user_id, password, password_read, salt, email, email_validated, last_name, name, number_phone, temp_token) VALUES (1, 0x5926ABD60C73A47B74FC6E9B8BEC7AE82F909C52634B8087BE3761536BD0F9B592A55709466FDC0930E6C7381A07B149981B581673CBBDE0B9178268539884DE, N'123', N'5òø\ÔºþC=ÜûEH^?ôö¡EYÙ¯°*¿ÊIT´%Ä(¨6}ÜK oV ', N'giovannyandresch@gmail.com', 0, N'Cortés Hernández', N'Giovanny Andrés', N'628 638 560', N'')
GO
ALTER TABLE ADMINS  WITH CHECK ADD  CONSTRAINT FK_ADMINS_HAIRDRESSERS FOREIGN KEY(hairdresser_id)
REFERENCES HAIRDRESSERS (hairdresser_id)
GO
ALTER TABLE ADMINS CHECK CONSTRAINT FK_ADMINS_HAIRDRESSERS
GO
ALTER TABLE ADMINS  WITH CHECK ADD  CONSTRAINT FK_ADMINS_USERS FOREIGN KEY(user_id)
REFERENCES USERS (user_id)
GO
ALTER TABLE ADMINS CHECK CONSTRAINT FK_ADMINS_USERS
GO
ALTER TABLE APPOINTMENT_SERVICES  WITH CHECK ADD  CONSTRAINT FK_APPOINTMENT_SERVICES_APPOINTMENTS FOREIGN KEY(appointment_id)
REFERENCES APPOINTMENTS (appointment_id)
GO
ALTER TABLE APPOINTMENT_SERVICES CHECK CONSTRAINT FK_APPOINTMENT_SERVICES_APPOINTMENTS
GO
ALTER TABLE APPOINTMENT_SERVICES  WITH CHECK ADD  CONSTRAINT FK_APPOINTMENT_SERVICES_SERVICES FOREIGN KEY(service_id)
REFERENCES SERVICES (service_id)
GO
ALTER TABLE APPOINTMENT_SERVICES CHECK CONSTRAINT FK_APPOINTMENT_SERVICES_SERVICES
GO
ALTER TABLE APPOINTMENTS  WITH CHECK ADD  CONSTRAINT FK_APPOINTMENTS_HAIRDRESSERS FOREIGN KEY(hairdresser_id)
REFERENCES HAIRDRESSERS (hairdresser_id)
GO
ALTER TABLE APPOINTMENTS CHECK CONSTRAINT FK_APPOINTMENTS_HAIRDRESSERS
GO
ALTER TABLE APPOINTMENTS  WITH CHECK ADD  CONSTRAINT FK_APPOINTMENTS_USERS FOREIGN KEY(user_id)
REFERENCES USERS (user_id)
GO
ALTER TABLE APPOINTMENTS CHECK CONSTRAINT FK_APPOINTMENTS_USERS
GO
ALTER TABLE SCHEDULE_ROWS  WITH CHECK ADD  CONSTRAINT FK_SCHEDULE_ROWS_SCHEDULES FOREIGN KEY(schedule_id)
REFERENCES SCHEDULES (schedule_id)
GO
ALTER TABLE SCHEDULE_ROWS CHECK CONSTRAINT FK_SCHEDULE_ROWS_SCHEDULES
GO
ALTER TABLE SCHEDULES  WITH CHECK ADD  CONSTRAINT FK_SCHEDULES_HAIRDRESSERS FOREIGN KEY(hairdresser_id)
REFERENCES HAIRDRESSERS (hairdresser_id)
GO
ALTER TABLE SCHEDULES CHECK CONSTRAINT FK_SCHEDULES_HAIRDRESSERS
GO
ALTER TABLE SERVICES  WITH CHECK ADD  CONSTRAINT FK_SERVICES_HAIRDRESSERS FOREIGN KEY(hairdresser_id)
REFERENCES HAIRDRESSERS (hairdresser_id)
GO
ALTER TABLE SERVICES CHECK CONSTRAINT FK_SERVICES_HAIRDRESSERS
GO
/****** Object:  StoredProcedure SP_ASSIGN_TOKEN    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

    CREATE PROCEDURE SP_ASSIGN_TOKEN(@USER_ID INT, @TOKEN NVARCHAR(100))
    AS
	    UPDATE USERS SET TEMP_TOKEN = @TOKEN WHERE USER_ID = @USER_ID;
GO
/****** Object:  StoredProcedure SP_COMPARE_ROLE    Script Date: 17/04/2023 0:24:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
    CREATE PROCEDURE SP_COMPARE_ROLE(@HAIRDRESSER_ID INT, @USER_ID1 INT, @USER_ID2 INT, @RES BIT OUT)
    AS
	    DECLARE @ROLE_1 INT, @ROLE_2 INT;
	    SELECT @ROLE_1 = ADMINS.role FROM ADMINS WHERE ADMINS.user_id = @USER_ID1 AND ADMINS.hairdresser_id = @HAIRDRESSER_ID;
	    SELECT @ROLE_2 = ADMINS.role FROM ADMINS WHERE ADMINS.user_id = @USER_ID2 AND ADMINS.hairdresser_id = @HAIRDRESSER_ID;
	    IF(@ROLE_1 <= @ROLE_2)
		    SET @RES = 1;
	    ELSE
		    SET @RES = 0;
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Estado de la cita (NoConfirmada = 0, Finalizada = 1, Activa = 2, Cancelada = 3)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'APPOINTMENTS', @level2type=N'COLUMN',@level2name=N'status'
GO
